kind: pipeline
name: build image

steps:
- name: build image
  image: vmck/vmck:0.0.2
  privileged: true
  volumes:
  - name: vmck-images
    path: /vmck-images
  commands:
  - IMAGE_NAME=imgbuild-$(echo $DRONE_COMMIT_BRANCH | tr -s '/' '_').qcow2
  - SCRIPT=/drone/src/scripts/$(echo $DRONE_COMMIT_BRANCH | cut -f1 -d'/').sh
  - ARCHIVE_TMP=/vmck-images/$IMAGE_NAME__tmp.tar.gz
  - ARCHIVE=/vmck-images/$IMAGE_NAME.tar.gz
  - env
  - ls -al $SCRIPT
  - mkdir /tmp/img
  - /opt/vmck/contrib/build.py /tmp/$IMAGE_NAME --script $SCRIPT
  - tar czvf $ARCHIVE_TMP -C /tmp $IMAGE_NAME
  - mv $ARCHIVE_TMP $ARCHIVE

volumes:
- name: vmck-images
  host:
      path: /opt/volumes/vmck-images
